const router = require('express').Router();
const {getReport, getPatient, setPatient, getPatients, getOldageHomeInfo,getDates,savePrecautions,getPrevReports,getreports,editPatient,image,login,removePatient,fetchDoctorsData} = require('./controllers/get_set')
const {getParameters,analysis,MedicalChatbotDoctor, llmanalysis,checkImage,MedicalChatbotPatient} = require('./controllers/LLM')
const {uploadpdf,pdfid,pdfparse,reciver,uploadXray}=require('./controllers/pdfs')
const {uploadstatement}=require('../backend/controllers/dummy')
router.get('/getreport/:id', getReport)
router.get('/image/:id',image)
router.post('/setPatient',setPatient)
router.get('/getpatient/:id', getPatient)
router.get('/getpatients', getPatients)
router.get('/getoldagehomeinfo', getOldageHomeInfo)
 router.post('/uploadpdf', uploadpdf)
 router.get('/pdfid/:id',pdfid)
 router.post('/pdfparse', pdfparse)
 router.post('/reciver',reciver)
 router.post('/getparameters',getParameters)
 router.post('/analysis',analysis);
 router.post('/llmanalysis', llmanalysis);
 router.get('/getdates/:id',getDates)
 router.post('/saveprecautions',savePrecautions)
 router.post('/getprevreports',getPrevReports)
 router.get('/getreports',getreports)
 router.post('/editPatient',editPatient)
 router.post('/MedicalChatbotDoctor',MedicalChatbotDoctor)
 router.post('/MedicalChatbotPatient',MedicalChatbotPatient)
 router.post('/login',login)
 router.post('/removepatient',removePatient)
 router.post('/checkImage',checkImage)
 router.post('/uploadXray',uploadXray)
 router.post('/consult',fetchDoctorsData)
 router.post('/uploadstatement',uploadstatement);
module.exports = router
